version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/data:/var/lib/postgresql/data
    networks:
      mynetwork:
        ipv4_address: 172.20.0.2

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8889:80"
    networks:
      mynetwork:
        ipv4_address: 172.20.0.3

  app:
    image: node:16
    working_dir: /src
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./:/src
    command: sh -c "npx nodemon -r dotenv/config src/app.js"
    networks:
      mynetwork:
        ipv4_address: 172.20.0.4

networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/24